version: '3.9'

services:
  api:
    container_name: MLH_Hackathons_API
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: unless-stopped
    ports:
      - "8002:80"
